#!/bin/sh

# haloopdy - 2026
# Just to make life easier: have a shell script that builds 
# when you expect that you're inside the docker container I added
# as part of the archipelago fork. This way if I need more stuff
# for archipelago, I don't have to worry about other stuff.

set -e
 
# Some defaults (also defined in the dockerfile but the dockerfile overrides these
# if you're building through that)
SDL2_VERSION="${SDL2_VERSION:-2.30.10}"
SDL2_DIR="${SDL2_DIR:-/opt/SDL2-${SDL2_VERSION}/i686-w64-mingw32}"
OPENSSL_VERSION="${OPENSSL_VERSION:-3.5.8}"
OPENSSL_DIR="${OPENSSL_DIR:-/opt/openssl-${OPENSSL_VERSION}/i686-w64-mingw32}"
BUILD_DIR="${BUILD_DIR:-pc/build32}"
 
if [ ! -d "$SDL2_DIR" ]; then
  echo "SDL2 not found at $SDL2_DIR" >&2
  echo "Set SDL2_DIR, or rebuild the docker image with --build-arg SDL2_VERSION=$SDL2_VERSION" >&2
  exit 1
fi

if [ ! -d "$OPENSSL_DIR" ]; then
  echo "OpenSSL not found at $OPENSSL_DIR" >&2
  echo "Set OPENSSL_DIR, or rebuild the docker image with --build-arg OPENSSL_VERSION=$OPENSSL_VERSION" >&2
  exit 1
fi

cmake -S pc -B "$BUILD_DIR" \
  -DCMAKE_TOOLCHAIN_FILE="$PWD/pc/cmake/Toolchain-mingw32.cmake" \
  -DCMAKE_PREFIX_PATH="$SDL2_DIR" \
  -DOPENSSL_ROOT_DIR="$OPENSSL_DIR" \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

cmake --build "$BUILD_DIR" -j"$(nproc)"

# I want to use compile_commands.json for my clang lsp but we need to do two things:
# - I don't want full rebuilds, so I can't modify anything the system depends on
# - I have to change /build to the actual directory on my machine.
# This means that, in order for your lsp to work, you need to build once.
if [ -n "$HOST_DIR" ] && [ -f "$BUILD_DIR/compile_commands.json" ]; then
  find "$BUILD_DIR" -name '*.rsp' | while read -r rsp; do
    sed "s|$PWD/|$HOST_DIR/|g" "$rsp" > "$rsp.host"
  done
  sed -i -e "s|$PWD/|$HOST_DIR/|g" \
         -e 's|\.rsp\.host|.rsp|g' \
         -e 's|\(@[^ ]*\.rsp\)|\1.host|g' "$BUILD_DIR/compile_commands.json"
fi

# The lsp also needs the mingw system headers (libstdc++ etc.) for apclient's C++, and those
# only exist inside the container. Copy the compiler's include search path out (mirroring the
# real paths under ignore/i686-w64-mingw32, outside the build graph so no rebuilds), then
# generate .clangd to match. .clangd is generated (and gitignored) because it needs absolute
# host paths. Delete ignore/i686-w64-mingw32 to refresh the copy (e.g. after a compiler upgrade).
if [ -n "$HOST_DIR" ]; then
  SYS_INC_DIR="ignore/i686-w64-mingw32"
  SYS_INC_LIST="$SYS_INC_DIR/include-paths.txt"  # search order matters (#include_next)
  if [ ! -f "$SYS_INC_LIST" ]; then
    rm -rf "$SYS_INC_DIR"
    mkdir -p "$SYS_INC_DIR"
    i686-w64-mingw32-g++ -E -x c++ - -v </dev/null 2>&1 \
      | sed -n '/^#include <...> search starts here:/,/^End of search list\./p' \
      | grep '^ ' | while read -r dir; do
          dir="$(realpath "$dir")"
          # gcc's own headers (intrinsics etc.) conflict with the ones clang ships
          case "$dir" in */lib/gcc/*/include | */include-fixed) continue ;; esac
          mkdir -p "$SYS_INC_DIR$dir"
          cp -rL "$dir/." "$SYS_INC_DIR$dir/"
          echo "$dir" >> "$SYS_INC_LIST"
        done
  fi

  # Same for the container-only OpenSSL and SDL2 headers
  SSL_INC_DIR="ignore/openssl-include"
  if [ ! -d "$SSL_INC_DIR" ]; then
    mkdir -p "$SSL_INC_DIR"
    cp -rL "$OPENSSL_DIR/include/." "$SSL_INC_DIR/"
  fi
  SDL_INC_DIR="ignore/sdl2-include"
  if [ ! -d "$SDL_INC_DIR" ]; then
    mkdir -p "$SDL_INC_DIR"
    cp -rL "$SDL2_DIR/include/." "$SDL_INC_DIR/"
  fi

  {
    echo "# Generated by build_mingw.sh, do not edit"
    echo "CompileFlags:"
    echo "  CompilationDatabase: pc/build32"
    echo "  Add:"
    echo "    - -isystem$HOST_DIR/$SDL_INC_DIR"
    echo "    - -isystem$HOST_DIR/$SDL_INC_DIR/SDL2"
    echo "    - -isystem$HOST_DIR/$SSL_INC_DIR"
    while read -r dir; do
      case "$dir" in */lib/gcc/*/include | */include-fixed) continue ;; esac
      echo "    - -isystem$HOST_DIR/$SYS_INC_DIR$dir"
    done < "$SYS_INC_LIST"
  } > .clangd
fi

cp "$SDL2_DIR/bin/SDL2.dll" "$BUILD_DIR/bin/"


# Third-party license text for statically linked OpenSSL
mkdir -p "$BUILD_DIR/bin/licenses"
cp "$OPENSSL_DIR/LICENSE.txt" "$BUILD_DIR/bin/licenses/OpenSSL-LICENSE.txt"
